# =======================================================================
# @file slam_toolbox_config.yaml
# @brief Configuration parameters for slam_toolbox mapping mode
#
# This file sets up SLAM Toolbox for 2D mapping using LiDAR scans and odometry.
# Adjust frame IDs, topics, performance, and loop closure settings as needed.
# =======================================================================

slam_toolbox:
  ros__parameters:
    # Frame conventions
    odom_frame: odom            # Odometry frame
    map_frame: map              # Global SLAM map frame
    base_frame: base_link       # Robot base frame

    # Input topic and mode
    scan_topic: /scan           # LiDAR scan topic
    mode: mapping               # 'mapping' for SLAM (vs 'localization')
    use_sim_time: false         # Use /clock topic for simulation time

    # -------------------------------------------------------------------
    # Timing settings
    odom_rate: 20.0             # Expected odometry update rate [Hz]
    scan_period: 0.13           # LiDAR scan interval [s]

    # -------------------------------------------------------------------
    # Map resolution and scan filtering
    resolution: 0.05            # Map grid cell size [m]
    max_laser_range: 15.0       # Maximum range to incorporate [m]
    min_laser_range: 0.2        # Minimum valid scan range [m]

    # Scan buffer
    scan_buffer_size: 5         # Number of scans to buffer for matching

    # -------------------------------------------------------------------
    # Correlative scan matcher parameters
    solver_plugin: "solver_plugins::CeresSolver"
    ceres_linear_solver: "SPARSE_NORMAL_CHOLESKY"
    ceres_max_num_iterations: 15 # Iterations for Ceres optimization

    # -------------------------------------------------------------------
    # Loop closure constraints
    loop_closure_detection: true   # Enable loop closure detection
    loop_closure_search_radius: 2.0    # Search radius [m]
    loop_closure_search_interval: 10   # Interval between checks [scans]
    min_constraint_score: 0.55        # Minimum match score for constraint

    # -------------------------------------------------------------------
    # Pose graph optimization
    max_submaps_to_keep: 3            # Retain last N submaps
    pose_graph:
      optimize_every_n_nodes: 20      # Optimize graph every N nodes
      max_constraint_distance: 2.0    # Max distance for constraints [m]

    # -------------------------------------------------------------------
    # Map publication
    publish_period_sec: 0.5           # Map update rate [s]
    publish_frame_projected_map: true # Publish map projected into 2D frame

#ros2 launch slam_toolbox online_async_launch.py   slam_params_file:=/home/genesis/Desktop/#Leonardo/src/mio_slam_toolbox/config/mapper_params_online_async.yaml

